### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mlocati** [concrete5/addon_community_translation#16]
Stuff yet to be done:

- [x] CLI command to automatically accept join requests older that X days (I currently do it manually on Transifex every 14 days)
- [X] Complete the REST api
- [X] Check that all notifications are placed int the queue
- [x] CLI command to send queued notifications
- [x] Intercept errors in CLI commands and send (email? slack? telegram?) notifications to site admins
